{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.secretName" . }}
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecretKey }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.groqApiKey }}
  GROQ_API_KEY: {{ .Values.secrets.groqApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
{{- end }}
